### PR TITLE
Fix Legal issues.

### PR DESCRIPTION
**Pull request by EliseZeroTwo**
Remove all source code. According to GPLV3 this code counts as stolen as it was not purposely distribute by its owner @Reisyukaku .

### CODE REVIEW

**Comment by goffrier** [comment]
epic

**Comment by ghost** [comment]
Just make a DMCA
That's sad for Rei

**Comment by KevinX8** [comment]
Report and move on. childish pull requests don't do anything.

**Comment by consnop** [comment]
Where does the GPL v3 mention stolen code?

**Comment by sandhoners123** [comment]
You cant bundle it with reinx as its source code would need to be public to anyone who uses your software.

**Comment by EliseZeroTwo** [comment]
Actually no @sandhoners123 this is incorrect. Deltalaunch is no longer licenced under GPLv3.

**Comment by sandhoners123** [comment]
Wait, what license are you using. ISC?

**Comment by sandhoners123** [comment]
The code you published now is GPL so you cant dcma it'

**Comment by EliseZeroTwo** [comment]
I actually don't have to disclose this information, nor will I as it isn't
my job to do so as I had nothing to do with Deltalaunch. Ask Rei if you
want to know.

**Comment by sandhoners123** [comment]
Well, it must be ISC since libnx is ISC and all apps link against libnx

**Comment by sandhoners123** [comment]
Why do you want to keep it private

**Comment by sandhoners123** [comment]
This is basically sx os

**Comment by noirscape** [comment]
Note: IANAL

The source code in question was originally located under the GPLv3. According to [estoppel](https://en.wikipedia.org/wiki/Estoppel), the fact that the original repository was left public and was licensed under the GPLv3 by the license holder (in this case I'm assuming that's Reisyukaku) means that this version of Deltalaunch will forever be under the GPLv3.

...there is no more to this. There is no legal issue here. As long as something has been made public under the GPLv3 legally once (which for the record, it is) that version will forever be under the GPLv3.

Reisyukaku is free to relicense this project in future commits to something closed source if he wants, considering he appears at least from the latest publicly visible commit to be the only author, but he cannot go back and claim that this publicly available version which is explicitly licensed under the GPLv3 is illegal.

**Pull request closed without merging**
